pull_request_rules:
  - name: Label
    conditions:
      - head=translations
      - author=Syjalo
    actions:
      label:
        add:
          - translations
  - name: Translations
    conditions:
      - head=translations
      - author=Syjalo
    actions:
      merge:
        method: squash
